name: ubuntu-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y ninja-build

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DRWMICRO_USE_OPENMP=OFF -DRWMICRO_BUILD_APPS=OFF -DRWMICRO_BUILD_TESTS=ON
      
      - name: Build
        run: |
          cd build
          cmake --build . --parallel 8

      - name: Run tests
        run: ./build/tests/rwmicro_tests
